/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import MotoristaPassageiroVeiculo.Motorista;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pegad
 */
public class CadastroMotorista extends javax.swing.JFrame {
    static ArrayList<Motorista> listaMotoristas;
    private DefaultTableModel tableModel;

    /**
     * Creates new form CadastroMotorista
     */
    public CadastroMotorista() {
        initComponents();
        setLocationRelativeTo(null);
        listaMotoristas = new ArrayList();
        
        // habilitar ou desabilitar botões
        btnNovoMotorista.setEnabled(true);
        btnSalvarDadosMotorista.setEnabled(false);
        btnCancelarMotorista.setEnabled(false);
        btnEditarMotorista.setEnabled(false);
        btnExcluirDadosMotorista.setEnabled(false);
        btnPesquisarMotorista.setEnabled(true);
        btnOkMotorista.setEnabled(false);
        
         // habilitar ou desabilitar texto
         txtIDMotorista.setEnabled(false);
         txtNomeMotorista.setEnabled(false);
         txtTelefoneMotorista.setEnabled(false);
         txtCNHMotorista.setEnabled(false);
    }
public void carregarDadosTabelaMotorista() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"ID", "Nome", "Telefone", "CNH"}, 0);
        
        for (int i = 0; i < listaMotoristas.size(); i++) {
            Object linha[] = new Object[] {listaMotoristas.get(i).getId(),
                                           listaMotoristas.get(i).getNome_motorista(),
                                           listaMotoristas.get(i).getTelefone_motorista(),
                                           listaMotoristas.get(i).getCnh()};
                                           
            modelo.addRow(linha);
                    }
        tblMotoristas.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDMotorista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeMotorista = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefoneMotorista = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCNHMotorista = new javax.swing.JTextField();
        btnOkMotorista = new javax.swing.JButton();
        btnSalvarDadosMotorista = new javax.swing.JButton();
        btnCancelarMotorista = new javax.swing.JButton();
        btnEditarMotorista = new javax.swing.JButton();
        btnExcluirDadosMotorista = new javax.swing.JButton();
        btnPesquisarMotorista = new javax.swing.JButton();
        btnNovoMotorista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMotoristas = new javax.swing.JTable();
        btnSairMotorista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Motorista");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/taxi_icon_187780.png")).getImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Motorista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel1.setText("ID:");

        txtIDMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDMotoristaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("CNH:");

        btnOkMotorista.setText("Ok");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIDMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOkMotorista))
                    .addComponent(txtNomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNHMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkMotorista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtCNHMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnSalvarDadosMotorista.setText("Salvar");
        btnSalvarDadosMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDadosMotoristaActionPerformed(evt);
            }
        });

        btnCancelarMotorista.setText("Cancelar");
        btnCancelarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMotoristaActionPerformed(evt);
            }
        });

        btnEditarMotorista.setText("Editar");
        btnEditarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMotoristaActionPerformed(evt);
            }
        });

        btnExcluirDadosMotorista.setText("Excluir");
        btnExcluirDadosMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDadosMotoristaActionPerformed(evt);
            }
        });

        btnPesquisarMotorista.setText("Pesquisar");
        btnPesquisarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarMotoristaActionPerformed(evt);
            }
        });

        btnNovoMotorista.setText("Novo");
        btnNovoMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoMotoristaActionPerformed(evt);
            }
        });

        tblMotoristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone", "CNH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMotoristas);

        btnSairMotorista.setText("Sair");
        btnSairMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairMotoristaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnNovoMotorista)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvarDadosMotorista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelarMotorista)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarMotorista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluirDadosMotorista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisarMotorista))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(338, 338, 338)
                                .addComponent(btnSairMotorista)))
                        .addGap(0, 246, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisarMotorista)
                    .addComponent(btnExcluirDadosMotorista)
                    .addComponent(btnEditarMotorista)
                    .addComponent(btnNovoMotorista)
                    .addComponent(btnSalvarDadosMotorista)
                    .addComponent(btnCancelarMotorista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairMotorista)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMotoristaActionPerformed

    private void btnPesquisarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarMotoristaActionPerformed

    private void btnNovoMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoMotoristaActionPerformed
        btnNovoMotorista.setEnabled(false);
        btnSalvarDadosMotorista.setEnabled(true);
        btnCancelarMotorista.setEnabled(true);
        btnEditarMotorista.setEnabled(false);
        btnExcluirDadosMotorista.setEnabled(false);
        btnPesquisarMotorista.setEnabled(false);
        btnOkMotorista.setEnabled(false);
        
         // habilitar ou desabilitar texto
         txtIDMotorista.setEnabled(true);
         txtNomeMotorista.setEnabled(true);
         txtTelefoneMotorista.setEnabled(true);
         txtCNHMotorista.setEnabled(true);
         
         txtIDMotorista.requestFocus();
    }//GEN-LAST:event_btnNovoMotoristaActionPerformed

    private void btnEditarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMotoristaActionPerformed

    private void btnSairMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairMotoristaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSairMotoristaActionPerformed

    private void btnSalvarDadosMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDadosMotoristaActionPerformed
        if (txtIDMotorista.getText().equals("" ) || txtNomeMotorista.getText().equals("") || 
                txtTelefoneMotorista.getText().equals("") || 
                txtCNHMotorista.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        else {
             // get de dados
            int id = Integer.parseInt(txtIDMotorista.getText());
            String nome = txtNomeMotorista.getText();
            String telefone = txtTelefoneMotorista.getText();
            String cnh = txtCNHMotorista.getText();

            Motorista motorista = new Motorista(id, nome, telefone, cnh);
            
            listaMotoristas.add(motorista);
            
            carregarDadosTabelaMotorista();

            JOptionPane.showMessageDialog(null, "Passageiro cadastrado com sucesso", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            
                // habilitar ou desabilitar botões
                btnNovoMotorista.setEnabled(true);
                btnSalvarDadosMotorista.setEnabled(false);
                btnCancelarMotorista.setEnabled(false);
                btnEditarMotorista.setEnabled(false);
                btnExcluirDadosMotorista.setEnabled(false);
                btnPesquisarMotorista.setEnabled(true);
                btnOkMotorista.setEnabled(false);

                 // habilitar ou desabilitar texto
                 txtIDMotorista.setEnabled(false);
                 txtNomeMotorista.setEnabled(false);
                 txtTelefoneMotorista.setEnabled(false);
                 txtCNHMotorista.setEnabled(false);

                 // limpar campos
                 txtIDMotorista.setText("");
                 txtNomeMotorista.setText("");
                 txtTelefoneMotorista.setText("");
                 txtCNHMotorista.setText("");
        }
    }//GEN-LAST:event_btnSalvarDadosMotoristaActionPerformed

    private void btnCancelarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMotoristaActionPerformed
        // limpar campos
         txtIDMotorista.setText("");
         txtNomeMotorista.setText("");
         txtTelefoneMotorista.setText("");
         txtCNHMotorista.setText("");

        // habilitar ou desabilitar botões
        btnNovoMotorista.setEnabled(true);
        btnSalvarDadosMotorista.setEnabled(false);
        btnCancelarMotorista.setEnabled(false);
        btnEditarMotorista.setEnabled(false);
        btnExcluirDadosMotorista.setEnabled(false);
        btnPesquisarMotorista.setEnabled(true);
        btnOkMotorista.setEnabled(false);
        
         // habilitar ou desabilitar texto
         txtIDMotorista.setEnabled(false);
         txtNomeMotorista.setEnabled(false);
         txtTelefoneMotorista.setEnabled(false);
         txtCNHMotorista.setEnabled(false);
    }//GEN-LAST:event_btnCancelarMotoristaActionPerformed

    private void btnExcluirDadosMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirDadosMotoristaActionPerformed
         // limpar campos
         txtIDMotorista.setText("");
         txtNomeMotorista.setText("");
         txtTelefoneMotorista.setText("");
         txtCNHMotorista.setText("");

        // habilitar ou desabilitar botões
        btnNovoMotorista.setEnabled(true);
        btnSalvarDadosMotorista.setEnabled(false);
        btnCancelarMotorista.setEnabled(false);
        btnEditarMotorista.setEnabled(false);
        btnExcluirDadosMotorista.setEnabled(false);
        btnPesquisarMotorista.setEnabled(true);
        btnOkMotorista.setEnabled(false);
        
         // habilitar ou desabilitar texto
         txtIDMotorista.setEnabled(false);
         txtNomeMotorista.setEnabled(false);
         txtTelefoneMotorista.setEnabled(false);
         txtCNHMotorista.setEnabled(false);
    }//GEN-LAST:event_btnExcluirDadosMotoristaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarMotorista;
    private javax.swing.JButton btnEditarMotorista;
    private javax.swing.JButton btnExcluirDadosMotorista;
    private javax.swing.JButton btnNovoMotorista;
    private javax.swing.JButton btnOkMotorista;
    private javax.swing.JButton btnPesquisarMotorista;
    private javax.swing.JButton btnSairMotorista;
    private javax.swing.JButton btnSalvarDadosMotorista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMotoristas;
    private javax.swing.JTextField txtCNHMotorista;
    private javax.swing.JTextField txtIDMotorista;
    private javax.swing.JTextField txtNomeMotorista;
    private javax.swing.JTextField txtTelefoneMotorista;
    // End of variables declaration//GEN-END:variables
}
