/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import MotoristaPassageiroVeiculo.Chamado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pegad
 */
public class FazerChamado extends javax.swing.JFrame {
    static ArrayList<Chamado> listaChamados;
    private DefaultTableModel tableModel;
    String botao;
    /**
     * Creates new form FazerChamado
     */
    public FazerChamado() {
        initComponents();
        setLocationRelativeTo(null);
        listaChamados = new ArrayList();
        
        // habilitar ou desabilitar botões
        btnSetNovoChamado.setEnabled(true);
        btnCadastrarChamado.setEnabled(false);
        btnCancelarRegistroChamada.setEnabled(false);
        btnEditarDadosChamado.setEnabled(false);
        btnExcluirDadosChamada.setEnabled(false);
        btnPesquisarChamado.setEnabled(true);
        btnOkChamado.setEnabled(false);
        
         // habilitar ou desabilitar texto
         txtIdChamado.setEnabled(false);
         txtDataChamado.setEnabled(false);
         txtOrigem.setEnabled(false);
         txtDestino.setEnabled(false);
         txtPartida.setEnabled(false);
         txtChegada.setEnabled(false);
         txtKmInicial.setEnabled(false);
         txtKmFinal.setEnabled(false);
         txtValorTotal.setEnabled(false);
    }
    
    public void carregarDadosTabelaChamado() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"ID", 
            "Data", "Origem", "Destino", "Partida", "Chegada", "Km Inicial", 
            "Km Final", "Total"}, 0);
        
        for (int i = 0; i < listaChamados.size(); i++) {
            Object linha[] = new Object[] {listaChamados.get(i).getId(),
                                           listaChamados.get(i).getData(),
                                           listaChamados.get(i).getOrigem(),
                                           listaChamados.get(i).getDestino(),
                                           listaChamados.get(i).getHorarioPartida(),
                                           listaChamados.get(i).getHorarioRetorno(),
                                           listaChamados.get(i).getKmInicial(),
                                           listaChamados.get(i).getKmFinal(),
                                           listaChamados.get(i).getValorTotal()};
            modelo.addRow(linha);
                    }
        tblChamados.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdChamado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataChamado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtOrigem = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtPartida = new javax.swing.JTextField();
        txtChegada = new javax.swing.JTextField();
        txtKmInicial = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        txtKmFinal = new javax.swing.JTextField();
        btnOkChamado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamados = new javax.swing.JTable();
        btnSetNovoChamado = new javax.swing.JButton();
        btnCadastrarChamado = new javax.swing.JButton();
        btnCancelarRegistroChamada = new javax.swing.JButton();
        btnEditarDadosChamado = new javax.swing.JButton();
        btnExcluirDadosChamada = new javax.swing.JButton();
        btnPesquisarChamado = new javax.swing.JButton();
        btnSairChamado = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chamar Taxi");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/taxi_icon_187780.png")).getImage());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados dos chamados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("ID:");

        jLabel2.setText("Data do chamado:");

        jLabel4.setText("Origem:");

        jLabel5.setText("Destino:");

        jLabel6.setText("Horário de partida:");

        jLabel7.setText("Horário de chegada:");

        jLabel8.setText("Km inicial:");

        jLabel9.setText("Km final:");

        jLabel10.setText("Valor total:");

        btnOkChamado.setText("Ok");
        btnOkChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkChamadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdChamado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(txtDataChamado, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOkChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKmInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKmFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(362, 362, 362))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDataChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOkChamado))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6))))
                    .addComponent(txtChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKmFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKmInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tblChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Tipo", "Origem", "Destino", "Partida", "Chegada", "Km Inicial", "Km Final", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChamadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChamados);

        btnSetNovoChamado.setText("Novo");
        btnSetNovoChamado.setToolTipText("Inserir um novo passageiro");
        btnSetNovoChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetNovoChamadoActionPerformed(evt);
            }
        });

        btnCadastrarChamado.setText("Salvar");
        btnCadastrarChamado.setToolTipText("Salvar os dados do passageiro");
        btnCadastrarChamado.setEnabled(false);
        btnCadastrarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarChamadoActionPerformed(evt);
            }
        });

        btnCancelarRegistroChamada.setText("Cancelar");
        btnCancelarRegistroChamada.setToolTipText("Cancelar a ação atual");
        btnCancelarRegistroChamada.setEnabled(false);
        btnCancelarRegistroChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegistroChamadaActionPerformed(evt);
            }
        });

        btnEditarDadosChamado.setText("Editar");
        btnEditarDadosChamado.setToolTipText("Selecione um passageiro da tabela para alterar seus dados");
        btnEditarDadosChamado.setEnabled(false);
        btnEditarDadosChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDadosChamadoActionPerformed(evt);
            }
        });

        btnExcluirDadosChamada.setText("Excluir");
        btnExcluirDadosChamada.setToolTipText("Selecione um passageiro da tabela para excluir seus dados");
        btnExcluirDadosChamada.setEnabled(false);
        btnExcluirDadosChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDadosChamadaActionPerformed(evt);
            }
        });

        btnPesquisarChamado.setText("Pesquisar");
        btnPesquisarChamado.setToolTipText("Pesquisar um passageiro");
        btnPesquisarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarChamadoActionPerformed(evt);
            }
        });

        btnSairChamado.setText("Sair");
        btnSairChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairChamadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSairChamado)
                .addGap(370, 370, 370))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnSetNovoChamado)
                        .addGap(38, 38, 38)
                        .addComponent(btnCadastrarChamado)
                        .addGap(39, 39, 39)
                        .addComponent(btnCancelarRegistroChamada)
                        .addGap(27, 27, 27)
                        .addComponent(btnEditarDadosChamado)
                        .addGap(30, 30, 30)
                        .addComponent(btnExcluirDadosChamada)
                        .addGap(29, 29, 29)
                        .addComponent(btnPesquisarChamado)
                        .addContainerGap(227, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetNovoChamado)
                    .addComponent(btnCadastrarChamado)
                    .addComponent(btnCancelarRegistroChamada)
                    .addComponent(btnEditarDadosChamado)
                    .addComponent(btnExcluirDadosChamada)
                    .addComponent(btnPesquisarChamado))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSairChamado)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetNovoChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetNovoChamadoActionPerformed
        botao = "novo";
        // limpar campos
        txtIdChamado.setText("");
        txtDataChamado.setText("");
        txtOrigem.setText("");
        txtDestino.setText("");
        txtPartida.setText("");
        txtChegada.setText("");
        txtKmInicial.setText("");
        txtKmFinal.setText("");
        txtValorTotal.setText("");
         
        // habilitar ou desabilitar botões
        btnSetNovoChamado.setEnabled(false);
        btnCadastrarChamado.setEnabled(true);
        btnCancelarRegistroChamada.setEnabled(true);
        btnEditarDadosChamado.setEnabled(false);
        btnExcluirDadosChamada.setEnabled(false);
        btnPesquisarChamado.setEnabled(false);
        

        // habilitar ou desabilitar texto
        txtIdChamado.setEnabled(true);
        txtDataChamado.setEnabled(true);
        txtOrigem.setEnabled(true);
        txtDestino.setEnabled(true);
        txtPartida.setEnabled(true);
        txtChegada.setEnabled(true);
        txtKmInicial.setEnabled(true);
        txtKmFinal.setEnabled(true);
        txtValorTotal.setEnabled(true);

        txtIdChamado.requestFocus();
    }//GEN-LAST:event_btnSetNovoChamadoActionPerformed

    private void btnCadastrarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarChamadoActionPerformed

         if (txtIdChamado.getText().equals("" ) || txtDataChamado.getText().equals("") || 
                txtOrigem.getText().equals("") || txtDestino.getText().equals("") || 
                txtPartida.getText().equals("") || 
                 txtChegada.getText().equals("")|| 
                 txtKmInicial.getText().equals("") || 
                 txtKmFinal.getText().equals("") || 
                 txtValorTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        else {
             // get de dados
            int id = Integer.parseInt(txtIdChamado.getText());
            String data = txtDataChamado.getText();
            String origem = txtOrigem.getText();
            String destino = txtDestino.getText();
            float partida = Float.parseFloat(txtPartida.getText());
            float chegada = Float.parseFloat(txtChegada.getText());
            Double kmInicial = Double.valueOf(txtKmInicial.getText());
            Double kmFinal = Double.valueOf(txtKmFinal.getText());
            Double valor = Double.valueOf(txtValorTotal.getText());
            
            if (botao.equals("novo")) {
                Chamado chamado = new Chamado(id, data, origem, destino, partida, chegada, kmInicial, kmFinal, valor);
            
                listaChamados.add(chamado);

                JOptionPane.showMessageDialog(null, "Chamado realizado com sucesso", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            }
            else if (botao.equals("editar")) {
                int i = tblChamados.getSelectedRow();
                
                listaChamados.get(i).setId(id);
                listaChamados.get(i).setData(data);
                listaChamados.get(i).setOrigem(origem);
                listaChamados.get(i).setDestino(destino);
                listaChamados.get(i).setHorarioPartida(partida);
                listaChamados.get(i).setHorarioRetorno(chegada);
                listaChamados.get(i).setKmInicial(kmInicial);
                listaChamados.get(i).setKmFinal(kmFinal);
                listaChamados.get(i).setValorTotal(valor);
                
                JOptionPane.showMessageDialog(null, "Registro alterado com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                 
            }
            
                carregarDadosTabelaChamado();
                    // habilitar ou desabilitar botões
                btnSetNovoChamado.setEnabled(true);
                btnCadastrarChamado.setEnabled(false);
                btnCancelarRegistroChamada.setEnabled(false);
                btnEditarDadosChamado.setEnabled(false);
                btnExcluirDadosChamada.setEnabled(false);
                btnPesquisarChamado.setEnabled(true);

                // habilitar ou desabilitar texto
                txtIdChamado.setEnabled(false);
                txtDataChamado.setEnabled(false);
                txtOrigem.setEnabled(false);
                txtDestino.setEnabled(false);
                txtPartida.setEnabled(false);
                txtChegada.setEnabled(false);
                txtKmInicial.setEnabled(false);
                txtKmFinal.setEnabled(false);
                txtValorTotal.setEnabled(false);
                 // limpar campos
                 txtIdChamado.setText("");
                txtDataChamado.setText("");
                txtOrigem.setText("");
                txtDestino.setText("");
                txtPartida.setText("");
                txtChegada.setText("");
                txtKmInicial.setText("");
                txtKmFinal.setText("");
                txtValorTotal.setText("");
        }
    }//GEN-LAST:event_btnCadastrarChamadoActionPerformed

    private void btnCancelarRegistroChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegistroChamadaActionPerformed
        // limpar campos
        txtIdChamado.setText("");
        txtDataChamado.setText("");
        txtOrigem.setText("");
        txtDestino.setText("");
        txtPartida.setText("");
        txtChegada.setText("");
        txtKmInicial.setText("");
        txtKmFinal.setText("");
        txtValorTotal.setText("");

        // habilitar ou desabilitar botões
        btnSetNovoChamado.setEnabled(true);
        btnCadastrarChamado.setEnabled(false);
        btnCancelarRegistroChamada.setEnabled(false);
        btnEditarDadosChamado.setEnabled(false);
        btnExcluirDadosChamada.setEnabled(false);
        btnPesquisarChamado.setEnabled(true);

        // habilitar ou desabilitar texto
        txtIdChamado.setEnabled(false);
        txtDataChamado.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtDestino.setEnabled(false);
        txtPartida.setEnabled(false);
        txtChegada.setEnabled(false);
        txtKmInicial.setEnabled(false);
        txtKmFinal.setEnabled(false);
        txtValorTotal.setEnabled(false);
    }//GEN-LAST:event_btnCancelarRegistroChamadaActionPerformed

    private void btnPesquisarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarChamadoActionPerformed
        if(listaChamados.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhuma chamada foi realizada", "Mensagem", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            txtIdChamado.setText("");
        txtDataChamado.setText("");
        txtOrigem.setText("");
        txtDestino.setText("");
        txtPartida.setText("");
        txtChegada.setText("");
        txtKmInicial.setText("");
        txtKmFinal.setText("");
        txtValorTotal.setText("");

        // habilitar ou desabilitar botões
        btnSetNovoChamado.setEnabled(false);
        btnCadastrarChamado.setEnabled(false);
        btnCancelarRegistroChamada.setEnabled(true);
        btnEditarDadosChamado.setEnabled(false);
        btnExcluirDadosChamada.setEnabled(false);
        btnPesquisarChamado.setEnabled(false);
        btnOkChamado.setEnabled(true);

        // habilitar ou desabilitar texto
        txtIdChamado.setEnabled(false);
        txtDataChamado.setEnabled(true);
        txtOrigem.setEnabled(false);
        txtDestino.setEnabled(false);
        txtPartida.setEnabled(false);
        txtChegada.setEnabled(false);
        txtKmInicial.setEnabled(false);
        txtKmFinal.setEnabled(false);
        txtValorTotal.setEnabled(false);
        
        txtIdChamado.requestFocus(); 
        }
       
    }//GEN-LAST:event_btnPesquisarChamadoActionPerformed

    private void btnSairChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairChamadoActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_btnSairChamadoActionPerformed

    private void btnOkChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkChamadoActionPerformed
        if (txtDataChamado.getText().equals("")) {
           JOptionPane.showMessageDialog(null, " A data do chamado deve ser informada!", "message", JOptionPane.INFORMATION_MESSAGE);
       }
       else {
           Chamado cha;
           String id = "";
           String dataChamado = "";
           String origem = "";
           String destino = "";
           String partida = "";
           String chegada = "";
           String kmInit = "";
           String kmFinit = "";
           String valorTot = "";
           String data = txtDataChamado.getText();
           
           for (int i = 0; i < listaChamados.size(); i++) {
                cha = listaChamados.get(i);
                if (data.equals(cha.getData())) {
                    id = String.valueOf(cha.getId());
                    dataChamado = cha.getData();
                    origem = cha.getOrigem();
                    destino = cha.getDestino();
                    partida = String.valueOf(cha.getHorarioPartida());
                    chegada = String.valueOf(cha.getHorarioRetorno());
                    kmInit = String.valueOf(cha.getKmInicial());
                    kmFinit = String.valueOf(cha.getKmFinal());
                    valorTot = String.valueOf(cha.getValorTotal());
                }
           }
           
           if (dataChamado.equals("")) {
                JOptionPane.showMessageDialog(null, " Essa data não pussui chamados", "message", JOptionPane.PLAIN_MESSAGE);
           }
           else {
               txtIdChamado.setText(id);
               txtDataChamado.setText(dataChamado);
               txtOrigem.setText(origem);
               txtDestino.setText(destino);
               txtPartida.setText(partida);
               txtChegada.setText(chegada);
               txtKmInicial.setText(kmInit);
               txtKmFinal.setText(kmFinit);
               txtValorTotal.setText(valorTot);
           }
            
       }
    }//GEN-LAST:event_btnOkChamadoActionPerformed

    private void tblChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChamadosMouseClicked
        int i = tblChamados.getSelectedRow();
        
        if (i >= 0 && i <= listaChamados.size()) {
            Chamado cha = listaChamados.get(i);
            txtIdChamado.setText(String.valueOf(cha.getId()));
            txtDataChamado.setText(String.valueOf(cha.getData()));
            txtOrigem.setText(String.valueOf(cha.getOrigem()));
            txtDestino.setText(String.valueOf(cha.getDestino()));
            txtPartida.setText(String.valueOf(cha.getHorarioPartida()));
            txtChegada.setText(String.valueOf(cha.getHorarioRetorno()));
            txtKmInicial.setText(String.valueOf(cha.getKmInicial()));
            txtKmFinal.setText(String.valueOf(cha.getKmFinal()));
            txtValorTotal.setText(String.valueOf(cha.getValorTotal()));
            
            btnSetNovoChamado.setEnabled(true);
            btnCadastrarChamado.setEnabled(false);
            btnCancelarRegistroChamada.setEnabled(false);
            btnEditarDadosChamado.setEnabled(true);
            btnExcluirDadosChamada.setEnabled(true);
            btnPesquisarChamado.setEnabled(true);
            }
        
    }//GEN-LAST:event_tblChamadosMouseClicked

    private void btnEditarDadosChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDadosChamadoActionPerformed
        botao = "editar";
        // habilitar ou desabilitar botoes
        
        btnSetNovoChamado.setEnabled(false);
        btnCadastrarChamado.setEnabled(true);
        btnCancelarRegistroChamada.setEnabled(true);
        btnEditarDadosChamado.setEnabled(false);
        btnExcluirDadosChamada.setEnabled(false);
        btnPesquisarChamado.setEnabled(false);
         // habilitar ou desabilitar texto
        txtIdChamado.setEnabled(true);
        txtDataChamado.setEnabled(true);
        txtOrigem.setEnabled(true);
        txtDestino.setEnabled(true);
        txtPartida.setEnabled(true);
        txtChegada.setEnabled(true);
        txtKmInicial.setEnabled(true);
        txtKmFinal.setEnabled(true);
        txtValorTotal.setEnabled(true);

        txtIdChamado.requestFocus();
    }//GEN-LAST:event_btnEditarDadosChamadoActionPerformed

    private void btnExcluirDadosChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirDadosChamadaActionPerformed
        int i = tblChamados.getSelectedRow();
        
        if (i >= 0 && i < listaChamados.size()) {
            listaChamados.remove(i);
            carregarDadosTabelaChamado();
        }
        // limpar campos
        txtIdChamado.setText("");
        txtDataChamado.setText("");
        txtOrigem.setText("");
        txtDestino.setText("");
        txtPartida.setText("");
        txtChegada.setText("");
        txtKmInicial.setText("");
        txtKmFinal.setText("");
        txtValorTotal.setText("");

        // habilitar ou desabilitar botões
        btnSetNovoChamado.setEnabled(true);
        btnCadastrarChamado.setEnabled(false);
        btnCancelarRegistroChamada.setEnabled(false);
        btnEditarDadosChamado.setEnabled(false);
        btnExcluirDadosChamada.setEnabled(false);
        btnPesquisarChamado.setEnabled(true);

        // habilitar ou desabilitar texto
        txtIdChamado.setEnabled(false);
        txtDataChamado.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtDestino.setEnabled(false);
        txtPartida.setEnabled(false);
        txtChegada.setEnabled(false);
        txtKmInicial.setEnabled(false);
        txtKmFinal.setEnabled(false);
        txtValorTotal.setEnabled(false);
    }//GEN-LAST:event_btnExcluirDadosChamadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FazerChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FazerChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FazerChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FazerChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FazerChamado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarChamado;
    private javax.swing.JButton btnCancelarRegistroChamada;
    private javax.swing.JButton btnEditarDadosChamado;
    private javax.swing.JButton btnExcluirDadosChamada;
    private javax.swing.JButton btnOkChamado;
    private javax.swing.JButton btnPesquisarChamado;
    private javax.swing.JButton btnSairChamado;
    private javax.swing.JButton btnSetNovoChamado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChamados;
    private javax.swing.JTextField txtChegada;
    private javax.swing.JTextField txtDataChamado;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtIdChamado;
    private javax.swing.JTextField txtKmFinal;
    private javax.swing.JTextField txtKmInicial;
    private javax.swing.JTextField txtOrigem;
    private javax.swing.JTextField txtPartida;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
