/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Pegad
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        mntCadastro = new javax.swing.JMenuItem();
        mntMotorista = new javax.swing.JMenuItem();
        mntVeiculo = new javax.swing.JMenuItem();
        jSeparatorMenuCadastro = new javax.swing.JPopupMenu.Separator();
        mntSair = new javax.swing.JMenuItem();
        mnChamarTaxi = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taxi Bacana");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/taxi_icon_187780.png")).getImage());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/taxi_icon_187780.png"))); // NOI18N
        jLabel1.setText("Taxi Bacana");

        mnCadastros.setMnemonic('c');
        mnCadastros.setText("Cadastro");

        mntCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3289576-individual-man-people-person_107097.png"))); // NOI18N
        mntCadastro.setMnemonic('p');
        mntCadastro.setText("Passageiro");
        mntCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntCadastroActionPerformed(evt);
            }
        });
        mnCadastros.add(mntCadastro);

        mntMotorista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/automobile_driver_drive_car_driving_icon_219752.png"))); // NOI18N
        mntMotorista.setMnemonic('m');
        mntMotorista.setText("Motorista");
        mntMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntMotoristaActionPerformed(evt);
            }
        });
        mnCadastros.add(mntMotorista);

        mntVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/car_13260.png"))); // NOI18N
        mntVeiculo.setMnemonic('v');
        mntVeiculo.setText("Veículo");
        mntVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntVeiculoActionPerformed(evt);
            }
        });
        mnCadastros.add(mntVeiculo);
        mnCadastros.add(jSeparatorMenuCadastro);

        mntSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/log_out_icon_197724.png"))); // NOI18N
        mntSair.setMnemonic('s');
        mntSair.setText("Sair");
        mntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntSairActionPerformed(evt);
            }
        });
        mnCadastros.add(mntSair);

        menuBar.add(mnCadastros);

        mnChamarTaxi.setText("Taxi");
        mnChamarTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChamarTaxiActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/car_13260.png"))); // NOI18N
        jMenuItem1.setText("Chamar Taxi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnChamarTaxi.add(jMenuItem1);

        menuBar.add(mnChamarTaxi);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(557, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntCadastroActionPerformed
        new CadastroPassageiros().setVisible(true);
    }//GEN-LAST:event_mntCadastroActionPerformed

    private void mntVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntVeiculoActionPerformed
        new CadastroVeiculo().setVisible(true);
    }//GEN-LAST:event_mntVeiculoActionPerformed

    private void mntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mntSairActionPerformed

    private void mntMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntMotoristaActionPerformed
        new CadastroMotorista().setVisible(true);
    }//GEN-LAST:event_mntMotoristaActionPerformed

    private void mnChamarTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChamarTaxiActionPerformed
        
    }//GEN-LAST:event_mnChamarTaxiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FazerChamado().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparatorMenuCadastro;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnChamarTaxi;
    private javax.swing.JMenuItem mntCadastro;
    private javax.swing.JMenuItem mntMotorista;
    private javax.swing.JMenuItem mntSair;
    private javax.swing.JMenuItem mntVeiculo;
    // End of variables declaration//GEN-END:variables
}
