/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import infosphere.Exemplar;
import infosphere.Localizacao;
import infosphere.Material;
import infosphere.TipoMateriais;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static telas.CadastroMateriais.material;

/**
 *
 * @author Pegad
 */
public class CadastroExemplares extends javax.swing.JFrame {

    /**
     * Creates new form exemplares
     */
    private ConsultaMateriais consultaMateriais;
    public CadastroExemplares() {
        initComponents();
        resetState();
    }
    
    private void clearText() {
        txtCodExemp.setText("");
        txfReimpr.setText("");
        txfRenovacoes.setText("");
    }
    
    private void resetState() {
        clearText();
        
        txtCodExemp.setEnabled(false);
        cmbLocalExemplar.setEnabled(false);
        txfReimpr.setEnabled(false);
        cbmLocalizacaoExemplar.setEnabled(false);
        txfRenovacoes.setEnabled(false);
        
        btnNovoExemplar.setEnabled(true);
        btnSalvarExemplar.setEnabled(false);
        btnEditarExemplar.setEnabled(false);
        btnExcluirMaterial.setEnabled(false);
        btnCancelarExemplar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtCodExemp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfReimpr = new javax.swing.JTextField();
        cbmLocalizacaoExemplar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfRenovacoes = new javax.swing.JTextField();
        btnNovoExemplar = new javax.swing.JButton();
        btnCancelarExemplar = new javax.swing.JButton();
        btnEditarExemplar = new javax.swing.JButton();
        btnSalvarExemplar = new javax.swing.JButton();
        btnExcluirMaterial = new javax.swing.JButton();
        btnSairExemplares = new javax.swing.JButton();
        cmbLocalExemplar = new javax.swing.JComboBox<>();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código de exemplar");

        jLabel2.setText("Disponibilidade");

        jLabel3.setText("Reimpressão");

        cbmLocalizacaoExemplar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acervo geral", "Obras raras", "Espaço som", "Multi-meios" }));

        jLabel4.setText("Localização");

        jLabel5.setText("Renovações");

        btnNovoExemplar.setText("Novo");
        btnNovoExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoExemplarActionPerformed(evt);
            }
        });

        btnCancelarExemplar.setText("Cancelar");
        btnCancelarExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarExemplarActionPerformed(evt);
            }
        });

        btnEditarExemplar.setText("Editar");

        btnSalvarExemplar.setText("Salvar");
        btnSalvarExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarExemplarActionPerformed(evt);
            }
        });

        btnExcluirMaterial.setText("Excluir");

        btnSairExemplares.setText("Sair");
        btnSairExemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairExemplaresActionPerformed(evt);
            }
        });

        cmbLocalExemplar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível", "Emprestado", "Processamento", "Restauro" }));
        cmbLocalExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLocalExemplarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodExemp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txfRenovacoes, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbmLocalizacaoExemplar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbLocalExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfReimpr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnNovoExemplar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarExemplar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarExemplar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarExemplar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirMaterial))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnSairExemplares)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodExemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbLocalExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfReimpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbmLocalizacaoExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfRenovacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoExemplar)
                    .addComponent(btnSalvarExemplar)
                    .addComponent(btnEditarExemplar)
                    .addComponent(btnCancelarExemplar)
                    .addComponent(btnExcluirMaterial))
                .addGap(35, 35, 35)
                .addComponent(btnSairExemplares)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void saveExemplares() {
        try {
            FileOutputStream fos = new FileOutputStream("exemplares.tmp");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(material);
            oos.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, String.format("Erro aconteceu enquanto tentava salvar exemplar: %s", e), "Mensagem", JOptionPane.PLAIN_MESSAGE);
            System.out.println(e);
        }
    }
    
    private void btnSalvarExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarExemplarActionPerformed
        consultaMateriais = new ConsultaMateriais();  
        if (txtCodExemp.getText().equals("" ) 
            || txfReimpr.getText().equals("") 
            || txfRenovacoes.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
             // get de dados
            String acervo = this.txtCodExemp.getText();
            Material materialSelecionado = consultaMateriais.getMaterialByAcervo(acervo);

            String reimpr = this.txfReimpr.getText();
            String localExemplar = String.valueOf(this.cmbLocalExemplar.getSelectedItem());
            String descricao = materialSelecionado.getDescricao();
            String edicao = materialSelecionado.getEdicao();
            String[] metadata = materialSelecionado.getMetadata();
            int numExemplares = materialSelecionado.getNumExemplares();
            TipoMateriais tipoMateriais = materialSelecionado.getTipoMateriais();
           
            Double valorMulta = 0.0;
            
            if(localExemplar.equals("Disponível")) {
                Boolean disponivel = true;
            }
            else {
               Boolean disponivel = false; 
            }

            // Obter a data de devolução convertendo a String para um objeto Date
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            String dataString = "01/01/2024"; // Data de exemplo
            Date dataDeDevolucao = null;
            try {
                dataDeDevolucao = df.parse(dataString);
            } catch (ParseException e) {
                e.printStackTrace();
            }

            Localizacao localizacao = Localizacao.valueOf(localExemplar.toUpperCase());
    
            // Criar o exemplar com os argumentos corrigidos
            Exemplar exemplar = new Exemplar(acervo, reimpr, materialSelecionado, dataDeDevolucao, valorMulta, descricao, edicao, metadata, numExemplares, localizacao, tipoMateriais);

        // Adicionar o exemplar ao material
        materialSelecionado.adicionarExemplar(exemplar);
            saveExemplares();
        }     
    }//GEN-LAST:event_btnSalvarExemplarActionPerformed

    private void btnSairExemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairExemplaresActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSairExemplaresActionPerformed

    private void cmbLocalExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLocalExemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLocalExemplarActionPerformed

    private void btnNovoExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoExemplarActionPerformed
        txtCodExemp.setEnabled(true);
        cmbLocalExemplar.setEnabled(true);
        txfReimpr.setEnabled(true);
        cbmLocalizacaoExemplar.setEnabled(true);
        txfRenovacoes.setEnabled(true);
        
        btnNovoExemplar.setEnabled(false);
        btnSalvarExemplar.setEnabled(true);
        btnEditarExemplar.setEnabled(false);
        btnExcluirMaterial.setEnabled(false);
        btnCancelarExemplar.setEnabled(true);
    }//GEN-LAST:event_btnNovoExemplarActionPerformed

    private void btnCancelarExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarExemplarActionPerformed
        resetState();
    }//GEN-LAST:event_btnCancelarExemplarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroExemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroExemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroExemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroExemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroExemplares().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarExemplar;
    private javax.swing.JButton btnEditarExemplar;
    private javax.swing.JButton btnExcluirMaterial;
    private javax.swing.JButton btnNovoExemplar;
    private javax.swing.JButton btnSairExemplares;
    private javax.swing.JButton btnSalvarExemplar;
    private javax.swing.JComboBox<String> cbmLocalizacaoExemplar;
    private javax.swing.JComboBox<String> cmbLocalExemplar;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txfReimpr;
    private javax.swing.JTextField txfRenovacoes;
    private javax.swing.JTextField txtCodExemp;
    // End of variables declaration//GEN-END:variables
}
