/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import infosphere.Exemplar;
import infosphere.Material;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pegad
 */
public class ConsultaMateriais extends javax.swing.JFrame {
    
    ArrayList<Material> materiais;
    ArrayList<Exemplar> exemplares;

    /**
     * Creates new form ConsultaMateriais
     */ 
    public ConsultaMateriais() {
        initComponents();
        
        this.loadMateriais();
        System.out.println(materiais);
        // loadExemplares();
        
        this.carregarDadosTabelaMaterial(); 
        
        btnNovoExemplar.setEnabled(false);
        btnEditarExemplar.setEnabled(false);
        btnDeletarExemplar.setEnabled(false);
        btnAcessarMaterial.setEnabled(false);
        btnExcluirMaterial.setEnabled(false);
        
        
        txfCodAcervo.setEnabled(false);
        txfTitulo.setEnabled(false);
        txfAutor.setEnabled(false);
        txaDescricao.setEnabled(false);
        cmbTipoMaterial.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMateriais = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txfSearchTitulo = new javax.swing.JTextField();
        btnSearchByTitulo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txfSearchCodAcervo = new javax.swing.JTextField();
        btnSearchByCodAcervo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfCodAcervo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaDescricao = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        cmbTipoMaterial = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txfAutor = new javax.swing.JTextField();
        btnAcessarMaterial = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblExemplares = new javax.swing.JTable();
        btnNovoMaterial = new javax.swing.JButton();
        btnExcluirMaterial = new javax.swing.JButton();
        btnNovoExemplar = new javax.swing.JButton();
        btnDeletarExemplar = new javax.swing.JButton();
        btnEditarExemplar = new javax.swing.JButton();
        btnSairMateriais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblMateriais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Edição", "Titulo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMateriais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMateriaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMateriais);

        jLabel5.setText("Titulo");

        btnSearchByTitulo.setText("ok");
        btnSearchByTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByTituloActionPerformed(evt);
            }
        });

        jLabel6.setText("Cód. Acervo");

        btnSearchByCodAcervo.setText("ok");
        btnSearchByCodAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByCodAcervoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(txfSearchCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txfSearchTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchByTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchByCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSearchTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByTitulo)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfSearchCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByCodAcervo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Título");

        jLabel2.setText("Código de acervo");

        jLabel3.setText("Descrição");

        txaDescricao.setColumns(20);
        txaDescricao.setRows(5);
        jScrollPane5.setViewportView(txaDescricao);

        jLabel7.setText("Tipo do material");

        cmbTipoMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livro", "Periódico", "Audiovisual", "Sonoro" }));

        jLabel4.setText("Autor");

        btnAcessarMaterial.setText("Acessar material");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btnAcessarMaterial)
                        .addGap(194, 194, 194))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAcessarMaterial))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tblExemplares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cód.exemp", "Reimpressão", "Disponível", "Localização", "Núm. renov"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblExemplares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExemplaresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblExemplares);

        btnNovoMaterial.setText("Novo material");
        btnNovoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoMaterialActionPerformed(evt);
            }
        });

        btnExcluirMaterial.setText("Excluir material");

        btnNovoExemplar.setText("Novo exemplar");
        btnNovoExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoExemplarActionPerformed(evt);
            }
        });

        btnDeletarExemplar.setText("Deletar exemplar");

        btnEditarExemplar.setText("Editar exemplar");
        btnEditarExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarExemplarActionPerformed(evt);
            }
        });

        btnSairMateriais.setText("Sair");
        btnSairMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairMateriaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(btnNovoMaterial)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluirMaterial))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(278, 278, 278)
                                        .addComponent(btnSairMateriais)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnNovoExemplar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarExemplar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeletarExemplar)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoMaterial)
                    .addComponent(btnExcluirMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoExemplar)
                    .addComponent(btnEditarExemplar)
                    .addComponent(btnDeletarExemplar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairMateriais)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadMateriais() {
        File materiaisFile = new File("materials.tmp");
        if(!materiaisFile.exists() || materiaisFile.isDirectory()) { 
            System.out.println("Não existem materiais ainda.");
            
            this.materiais = new ArrayList();
            return;
        }
        
        try {
            FileInputStream fis = new FileInputStream("materials.tmp");
            ObjectInputStream ois = new ObjectInputStream(fis);
            
            ArrayList<Material> loadedMateriais = (ArrayList<Material>) ois.readObject();
            
            System.out.println("Materiais encontrados");
            System.out.println(loadedMateriais);
            
            this.materiais = loadedMateriais;
            
            ois.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, String.format("Erro aconteceu enquanto tentava carregar materiais: %s", e), "Mensagem", JOptionPane.PLAIN_MESSAGE);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, String.format("Arquivo de materiais corrompido: %s", e), "Mensagem", JOptionPane.PLAIN_MESSAGE);
        }
    }
 
    private void loadExemplares() {
        File exemplaresFile = new File("exemplares.tmp");
        if(!exemplaresFile.exists() || exemplaresFile.isDirectory()) { 
            this.exemplares = new ArrayList();
            return;
        }
        
        try {
            FileInputStream fis = new FileInputStream("exemplares.tmp");
            ObjectInputStream ois = new ObjectInputStream(fis);
            ArrayList<Exemplar> loadedMateriais = (ArrayList<Exemplar>) ois.readObject();
            this.exemplares = loadedMateriais;
            
            ois.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, String.format("Erro aconteceu enquanto tentava carregar exemplares: %s", e), "Mensagem", JOptionPane.PLAIN_MESSAGE);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, String.format("Arquivo de exemplares corrompido: %s", e), "Mensagem", JOptionPane.PLAIN_MESSAGE);
        }
    }
    
    private void carregarDadosTabelaMaterial() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Edição", "Título"}, 0);
           
        System.out.println(materiais);
        for (int i = 0; i < this.materiais.size(); i++) {
            Object linha[] = new Object[] {
                this.materiais.get(i).getEdicao(),
                this.materiais.get(i).getNome(),
            };
            modelo.addRow(linha);
        }
        
        tblMateriais.setModel(modelo);
        // carregarDadosTabelaExemplares();
    }
    
    private void carregarDadosTabelaExemplares() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Cód. Exemplar", 
            "Reimpressão", "Disponível", "Localização", "Núm. renov"}, 0);

        // Itera sobre os materiais para acessar os exemplares de cada material
        for (Material mat : this.materiais) {
            List<Exemplar> exemplaresMaterial = mat.getExemplaresMaterial();
            for (Exemplar ex : exemplaresMaterial) {
                Object linha[] = new Object[] {
                    ex.getCodigoExemplar(),
                    ex.getReimpr(),
                    ex.isEmprestado(),
                    ex.getLocalizacao(),
                    ex.getRenovacoes(),
                };
                modelo.addRow(linha);
            }
        }
        
        tblExemplares.setModel(modelo);
    }

    private void carregarTabelaMateriaisFiltrada(String titulo, String codAcervo) {
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Edicao", "Título"}, 0);
        
        for (int i = 0; i < this.materiais.size(); i++){
            if (this.materiais.get(i).getNome().toLowerCase().contains(titulo.toLowerCase())
                    || this.materiais.get(i).getCodigoAcervo().contains(codAcervo)
            ) {
                Object[] linha = new Object[]{
                    this.materiais.get(i).getEdicao(),
                    this.materiais.get(i).getNome()
                };

                modelo.addRow(linha);
                carregarDadosTabelaExemplares();
            }
        }
        
        tblMateriais.setModel(modelo);
    }
    
    private void btnSearchByTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByTituloActionPerformed
        String titulo = txfSearchTitulo.getText();
        carregarTabelaMateriaisFiltrada(titulo, "");
    }//GEN-LAST:event_btnSearchByTituloActionPerformed

    private void btnSearchByCodAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByCodAcervoActionPerformed
        String codAcervo = txfSearchCodAcervo.getText();
        carregarTabelaMateriaisFiltrada("", codAcervo);
    }//GEN-LAST:event_btnSearchByCodAcervoActionPerformed

    private void btnNovoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoMaterialActionPerformed
        new CadastroMateriais().setVisible(true);
    }//GEN-LAST:event_btnNovoMaterialActionPerformed
    public Material getMaterialByAcervo(String cod) {
        for (int i = 0; i < this.materiais.size(); i++){
            if (this.materiais.get(i).getCodigoAcervo().contains(cod)) {
                return this.materiais.get(i);
            }
        }
          return null;
    }
    
    private void btnNovoExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoExemplarActionPerformed
        CadastroExemplares cadastroExemplares = new CadastroExemplares();
        cadastroExemplares.setVisible(true);
    }//GEN-LAST:event_btnNovoExemplarActionPerformed

    private void tblMateriaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMateriaisMouseClicked
        int i = tblMateriais.getSelectedRow();
        
        txfCodAcervo.setText(this.materiais.get(i).getCodigoAcervo());
        txfTitulo.setText(this.materiais.get(i).getNome());
        txfAutor.setText(this.materiais.get(i).getAutor());
        txaDescricao.setText(this.materiais.get(i).getDescricao());
        cmbTipoMaterial.setSelectedItem(this.materiais.get(i).getTipoMateriais());
        
        btnNovoExemplar.setEnabled(true);
        btnEditarExemplar.setEnabled(false);
        btnDeletarExemplar.setEnabled(false);
        btnAcessarMaterial.setEnabled(true);
        
        txfCodAcervo.setEnabled(false);
        txfTitulo.setEnabled(false);
        txfAutor.setEnabled(false);
        txaDescricao.setEnabled(false);
        cmbTipoMaterial.setEnabled(false);
        
        btnExcluirMaterial.setEnabled(true);
        
    }//GEN-LAST:event_tblMateriaisMouseClicked

    private void btnSairMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairMateriaisActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSairMateriaisActionPerformed

    private void tblExemplaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExemplaresMouseClicked
        int i = tblExemplares.getSelectedRow();
        btnEditarExemplar.setEnabled(true);
        btnExcluirMaterial.setEnabled(true);
        //get(i).setId(id);
    }//GEN-LAST:event_tblExemplaresMouseClicked

    private void btnEditarExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarExemplarActionPerformed
        int i = tblExemplares.getSelectedRow();
        
    }//GEN-LAST:event_btnEditarExemplarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaMateriais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessarMaterial;
    private javax.swing.JButton btnDeletarExemplar;
    private javax.swing.JButton btnEditarExemplar;
    private javax.swing.JButton btnExcluirMaterial;
    private javax.swing.JButton btnNovoExemplar;
    private javax.swing.JButton btnNovoMaterial;
    private javax.swing.JButton btnSairMateriais;
    private javax.swing.JButton btnSearchByCodAcervo;
    private javax.swing.JButton btnSearchByTitulo;
    private javax.swing.JComboBox<String> cmbTipoMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblExemplares;
    private javax.swing.JTable tblMateriais;
    private javax.swing.JTextArea txaDescricao;
    private javax.swing.JTextField txfAutor;
    private javax.swing.JTextField txfCodAcervo;
    private javax.swing.JTextField txfSearchCodAcervo;
    private javax.swing.JTextField txfSearchTitulo;
    private javax.swing.JTextField txfTitulo;
    // End of variables declaration//GEN-END:variables
}
