/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import infosphere.Material;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pegad
 */
public class Materiais extends javax.swing.JFrame {
    static ArrayList<Material> listaMateriais;
    String[] metadata = new String[6];
    //String[] tiposDeMateriais = {"Livros", "Periódicos", "Lúdicos", "Audiovisuais", "Sonoros"};
    String botao;
    /**
     * Creates new form Materiais
     */
    public Materiais() {
        initComponents();
        listaMateriais = new ArrayList();
        
        // habilitar ou desabilitar botões
       /* btnNovoMaterial.setEnabled(true);
        btnSalvarMaterial.setEnabled(false);
        btnCancelarMaterial.setEnabled(false);
        btnEditarMaterial.setEnabled(false);
        btnExcluirMaterial.setEnabled(false);
        btnPesquisarMaterial.setEnabled(true);
        btnOkMaterial.setEnabled(false);

        // habilitar ou desabilitar texto
        txtCodAcervo.setEnabled(false);
        txtNomeMaterial.setEnabled(false);
        txaDescricaoMaterial.setEnabled(false);
        txtTitulo.setEnabled(false);
        //txtTipo.setEnabled(false);
        txtEditora.setEnabled(false);
        txtAutores.setEnabled(false);
        txtAnoPublicacao.setEnabled(false);
        txtClassificacaoIndicativa.setEnabled(false);
        txtIdioma.setEnabled(false);
        txtQuantExemplares.setEnabled(false);
        */
    }
    
    public void carregarDadosTabelaMaterial() {
       /* DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Acervo", 
            "Nome", "Tipo", "Número de exemplares"}, 0);
        
        for (int i = 0; i < listaMateriais.size(); i++) {
            Object linha[] = new Object[] {listaMateriais.get(i).getCodigoAcervo(),
                                           listaMateriais.get(i).getNome(),
                                           listaMateriais.get(i).getTipoMaterial(),
                                           listaMateriais.get(i).getNumExemplares()};
            modelo.addRow(linha);
                    }
        tblMateriais.setModel(modelo);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMateriais = new javax.swing.JTable();
        btnFecharMaterial = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodAcervo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeMaterial = new javax.swing.JTextField();
        btnOkMaterial = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDescricaoMaterial = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtQuantExemplares = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnNovoMaterial = new javax.swing.JButton();
        btnSalvarMaterial = new javax.swing.JButton();
        btnEditarMaterial = new javax.swing.JButton();
        btnCancelarMaterial = new javax.swing.JButton();
        btnPesquisarMaterial = new javax.swing.JButton();
        btnExcluirMaterial = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Materiais");
        setAlwaysOnTop(true);

        tblMateriais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Acervo", "Nome", "Tipo", "Número de exemplares"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMateriais);

        btnFecharMaterial.setText("Sair");
        btnFecharMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharMaterialActionPerformed(evt);
            }
        });

        jLabel2.setText("Código de Acervo");

        jLabel3.setText("Nome");

        btnOkMaterial.setText("Pesquisar");
        btnOkMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkMaterialActionPerformed(evt);
            }
        });

        txaDescricaoMaterial.setColumns(20);
        txaDescricaoMaterial.setRows(5);
        jScrollPane2.setViewportView(txaDescricaoMaterial);

        jLabel4.setText("Descrição");

        jLabel5.setText("Tipo do material");

        jLabel11.setText("Quantidade de exemplares");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Cadastrar metadados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Pesquisar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOkMaterial)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantExemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(666, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNomeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButton1)))
                .addGap(0, 686, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(txtQuantExemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel1);

        btnNovoMaterial.setText("Novo");
        btnNovoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoMaterialActionPerformed(evt);
            }
        });

        btnSalvarMaterial.setText("Salvar");
        btnSalvarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarMaterialActionPerformed(evt);
            }
        });

        btnEditarMaterial.setText("Editar");
        btnEditarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMaterialActionPerformed(evt);
            }
        });

        btnCancelarMaterial.setText("Cancelar");
        btnCancelarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMaterialActionPerformed(evt);
            }
        });

        btnPesquisarMaterial.setText("Pesquisar");
        btnPesquisarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarMaterialActionPerformed(evt);
            }
        });

        btnExcluirMaterial.setText("Excluir");
        btnExcluirMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMaterialActionPerformed(evt);
            }
        });

        jButton2.setText("Exemplares");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(btnNovoMaterial)
                .addGap(41, 41, 41)
                .addComponent(btnSalvarMaterial)
                .addGap(44, 44, 44)
                .addComponent(btnEditarMaterial)
                .addGap(29, 29, 29)
                .addComponent(btnCancelarMaterial)
                .addGap(44, 44, 44)
                .addComponent(btnPesquisarMaterial)
                .addGap(55, 55, 55)
                .addComponent(btnExcluirMaterial)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jButton2)
                .addGap(192, 192, 192)
                .addComponent(btnFecharMaterial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoMaterial)
                    .addComponent(btnSalvarMaterial)
                    .addComponent(btnEditarMaterial)
                    .addComponent(btnCancelarMaterial)
                    .addComponent(btnPesquisarMaterial)
                    .addComponent(btnExcluirMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFecharMaterial))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoMaterialActionPerformed
        /*botao = "novo";
        // limpar campos
        txtCodAcervo.setText("");
        txtNomeMaterial.setText("");
        txaDescricaoMaterial.setText("");
        txtTitulo.setText("");
        txtTipo.setText("");
        txtAutores.setText("");
        txtAnoPublicacao.setText("");
        txtClassificacaoIndicativa.setText("");
        txtIdioma.setText("");
        txtEditora.setText("");
        txtQuantExemplares.setText("");
     
        // habilitar ou desabilitar botões
        btnNovoMaterial.setEnabled(false);
        btnSalvarMaterial.setEnabled(true);
        btnCancelarMaterial.setEnabled(true);
        btnEditarMaterial.setEnabled(false);
        btnExcluirMaterial.setEnabled(false);
        btnPesquisarMaterial.setEnabled(false);
        btnOkMaterial.setEnabled(false);

        // habilitar ou desabilitar texto
        txtCodAcervo.setEnabled(true);
        txtNomeMaterial.setEnabled(true);
        txaDescricaoMaterial.setEnabled(true);
        txtTitulo.setEnabled(true);
        txtEditora.setEnabled(true);
        txtTipo.setEnabled(true);
        txtAutores.setEnabled(true);
        txtAnoPublicacao.setEnabled(true);
        txtClassificacaoIndicativa.setEnabled(true);
        txtIdioma.setEnabled(true);
        txtQuantExemplares.setEnabled(true);

        txtCodAcervo.requestFocus();
        */
    }//GEN-LAST:event_btnNovoMaterialActionPerformed

    private void btnExcluirMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMaterialActionPerformed
      /* int i = tblMateriais.getSelectedRow();
        
        if (i >= 0 && i < listaMateriais.size()) {
            listaMateriais.remove(i);
            carregarDadosTabelaMaterial();
        }
        // limpar campos
        txtCodAcervo.setText("");
        txtNomeMaterial.setText("");
        txaDescricaoMaterial.setText("");
        txtTitulo.setText("");
        //txtTipo.setText("");
        txtAutores.setText("");
        txtAnoPublicacao.setText("");
        txtClassificacaoIndicativa.setText("");
        txtIdioma.setText("");
        txtEditora.setText("");
        txtQuantExemplares.setText("");

        // habilitar ou desabilitar botões
        btnSalvarMaterial.setEnabled(false);
        btnCancelarMaterial.setEnabled(false);
        btnEditarMaterial.setEnabled(false);
        btnExcluirMaterial.setEnabled(false);
        btnPesquisarMaterial.setEnabled(true);
        btnOkMaterial.setEnabled(false);

        // habilitar ou desabilitar texto
        txtCodAcervo.setEnabled(false);
        txtNomeMaterial.setEnabled(false);
        txaDescricaoMaterial.setEnabled(false);
        txtTitulo.setEnabled(false);
        //txtTipo.setEnabled(false);
        txtEditora.setEnabled(false);
        txtAutores.setEnabled(false);
        txtAnoPublicacao.setEnabled(false);
        txtClassificacaoIndicativa.setEnabled(false);
        txtIdioma.setEnabled(false);
        txtQuantExemplares.setEnabled(false);
        */
    }//GEN-LAST:event_btnExcluirMaterialActionPerformed

    private void btnOkMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkMaterialActionPerformed
        /*if (txtNomeMaterial.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "O nome do material deve ser informado", "message", JOptionPane.INFORMATION_MESSAGE);
       }
       else {
           Material mat;
           String cod = "";
           String nome = txtNomeMaterial.getText();
           String descricao = "";
           String tipo = "";
           String quantExemp = "";
           String tituloAlt = "";
           String idioma = "";
           String autor = "";
           String editora = "";
           String anoPublicacao = "";
           String classIndicativa = "";
           
           for (int i = 0; i < listaMateriais.size(); i++) {
                mat = listaMateriais.get(i);
                if (nome.equals(mat.getNome())) {
                    cod = String.valueOf(mat.getCodigoAcervo());
                    nome = mat.getNome();
                    descricao = mat.getDescricao();
                    tipo = mat.getTipoMaterial();
                    quantExemp = String.valueOf(mat.getNumExemplares());
                    tituloAlt = String.valueOf(mat.getMetadataByIndex(0));
                    idioma = String.valueOf(mat.getMetadataByIndex(1));
                    autor = String.valueOf(mat.getMetadataByIndex(2));
                    editora = String.valueOf(mat.getMetadataByIndex(3));
                    anoPublicacao = String.valueOf(mat.getMetadataByIndex(4));
                    classIndicativa = String.valueOf(mat.getMetadataByIndex(5));
                }
           }
           
           if (nome.equals("")) {
                JOptionPane.showMessageDialog(null, " Essa data não pussui chamados", "message", JOptionPane.PLAIN_MESSAGE);
           }
           else {
               txtCodAcervo.setText(cod);
                txtNomeMaterial.setText(nome);
                txaDescricaoMaterial.setText(descricao);
                txtTitulo.setText(tituloAlt);
                //txtTipo.setText(tipo);
                txtAutores.setText(autor);
                txtAnoPublicacao.setText(anoPublicacao);
                txtClassificacaoIndicativa.setText(classIndicativa);
                txtIdioma.setText(idioma);
                txtEditora.setText(editora);
                txtQuantExemplares.setText(quantExemp);
           }
            
       }*/
    }//GEN-LAST:event_btnOkMaterialActionPerformed

    private void btnSalvarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMaterialActionPerformed
         /*if (txtCodAcervo.getText().equals("" ) || txtNomeMaterial.getText().equals("") || 
                txaDescricaoMaterial.getText().equals("") || txtTitulo.getText().equals("") || 
                txtAutores.getText().equals("") || 
                txtAnoPublicacao.getText().equals("") || txtEditora.getText().equals("") ||
                txtClassificacaoIndicativa.getText().equals("") || txtIdioma.getText().equals("") ||
                txtQuantExemplares.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
             // get de dados
            String acervo = txtCodAcervo.getText();
            String nome = txtNomeMaterial.getText();
            String descricao = txaDescricaoMaterial.getText();
            String tituloAlternativo = txtTitulo.getText();
            //String tipo = txtTipo.getText();
            String autores = txtAutores.getText();
            String anoPublicacao = txtAnoPublicacao.getText();
            String  idioma = txtIdioma.getText();
            String editora = txtEditora.getText();
            String classificacaoEtaria = txtClassificacaoIndicativa.getText();
            int numExemplares = Integer.parseInt(txtQuantExemplares.getText());
            
            metadata[0] = tituloAlternativo;
            metadata[1] = autores;
            metadata[2] = anoPublicacao;
            metadata[3] = idioma;
            metadata[4] = editora;
            metadata[5] = classificacaoEtaria;
     
            if (botao.equals("novo")) {
                Material material = new Material(acervo, nome, descricao, tipo, metadata, numExemplares);
            
                listaMateriais.add(material);

                JOptionPane.showMessageDialog(null, "Material cadastrado com sucesso", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            }
            else if (botao.equals("editar")) {
                int i = tblMateriais.getSelectedRow();
                
                listaMateriais.get(i).setCodigoAcervo(acervo);
                listaMateriais.get(i).setNome(nome);
                //listaMateriais.get(i).setDescricao(descricao);
                listaMateriais.get(i).setNumExemplares(numExemplares);
                listaMateriais.get(i).setTipoMaterial(tipo);
  
                
                JOptionPane.showMessageDialog(null, "Registro alterado com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            }
            
                carregarDadosTabelaMaterial();
                // habilitar ou desabilitar botões
                btnNovoMaterial.setEnabled(true);
                btnSalvarMaterial.setEnabled(false);
                btnCancelarMaterial.setEnabled(false);
                btnEditarMaterial.setEnabled(false);
                btnExcluirMaterial.setEnabled(false);
                btnPesquisarMaterial.setEnabled(true);
                btnOkMaterial.setEnabled(false);

                // habilitar ou desabilitar texto
                txtCodAcervo.setEnabled(false);
                txtNomeMaterial.setEnabled(false);
                txaDescricaoMaterial.setEnabled(false);
                txtTitulo.setEnabled(false);
                txtAutores.setEnabled(false);
                txtAnoPublicacao.setEnabled(false);
                txtClassificacaoIndicativa.setEnabled(false);
                txtIdioma.setEnabled(false);
                txtQuantExemplares.setEnabled(false);
                 // limpar campos
                 txtCodAcervo.setText("");
                txtNomeMaterial.setText("");
                txaDescricaoMaterial.setText("");
                txtTitulo.setText("");
                txtAutores.setText("");
                txtAnoPublicacao.setText("");
                txtClassificacaoIndicativa.setText("");
                txtIdioma.setText("");
                txtEditora.setText("");
                txtQuantExemplares.setText("");
        }*/
    }//GEN-LAST:event_btnSalvarMaterialActionPerformed

    private void btnFecharMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharMaterialActionPerformed
         this.setVisible(false);
    }//GEN-LAST:event_btnFecharMaterialActionPerformed

    private void btnCancelarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMaterialActionPerformed
             // habilitar ou desabilitar botões
                /*btnNovoMaterial.setEnabled(true);
                btnSalvarMaterial.setEnabled(false);
                btnCancelarMaterial.setEnabled(false);
                btnEditarMaterial.setEnabled(false);
                btnExcluirMaterial.setEnabled(false);
                btnPesquisarMaterial.setEnabled(true);
                btnOkMaterial.setEnabled(false);

                // habilitar ou desabilitar texto
                txtCodAcervo.setEnabled(false);
                txtNomeMaterial.setEnabled(false);
                txaDescricaoMaterial.setEnabled(false);
                txtTitulo.setEnabled(false);
                txtAutores.setEnabled(false);
                txtEditora.setEnabled(false);
                //txtTipo.setEnabled(false);
                txtAnoPublicacao.setEnabled(false);
                txtClassificacaoIndicativa.setEnabled(false);
                txtIdioma.setEnabled(false);
                txtQuantExemplares.setEnabled(false);
                 // limpar campos
                 txtCodAcervo.setText("");
                txtNomeMaterial.setText("");
                txaDescricaoMaterial.setText("");
                txtTitulo.setText("");
                txtAutores.setText("");
                txtAnoPublicacao.setText("");
                txtClassificacaoIndicativa.setText("");
                txtIdioma.setText("");
                txtEditora.setText("");
                txtQuantExemplares.setText("");
                */
    }//GEN-LAST:event_btnCancelarMaterialActionPerformed

    private void btnEditarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMaterialActionPerformed
       /* botao = "editar";
        // habilitar ou desabilitar botoes
        btnNovoMaterial.setEnabled(false);
        btnSalvarMaterial.setEnabled(true);
        btnCancelarMaterial.setEnabled(true);
        btnEditarMaterial.setEnabled(false);
        btnExcluirMaterial.setEnabled(false);
        btnPesquisarMaterial.setEnabled(false);
        btnOkMaterial.setEnabled(false);
        // habilitar ou desabilitar texto
        txtCodAcervo.setEnabled(true);
        txtNomeMaterial.setEnabled(true);
        txaDescricaoMaterial.setEnabled(true);
        txtTitulo.setEnabled(true);
        txtEditora.setEnabled(false);
        //txtTipo.setEnabled(false);
        txtAutores.setEnabled(true);
        txtAnoPublicacao.setEnabled(true);
        txtClassificacaoIndicativa.setEnabled(true);
        txtIdioma.setEnabled(true);
        txtQuantExemplares.setEnabled(true);

        txtCodAcervo.requestFocus();
        */
    }//GEN-LAST:event_btnEditarMaterialActionPerformed

    private void btnPesquisarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarMaterialActionPerformed
       /* if(listaMateriais.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum material foi cadastrado", "Mensagem", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            txtCodAcervo.setText("");
            txtNomeMaterial.setText("");
            txaDescricaoMaterial.setText("");
            txtTitulo.setText("");
            txtAutores.setText("");
            txtAnoPublicacao.setText("");
            txtClassificacaoIndicativa.setText("");
            txtIdioma.setText("");
            txtEditora.setText("");
            txtQuantExemplares.setText("");

        // habilitar ou desabilitar botões
        btnNovoMaterial.setEnabled(false);
        btnSalvarMaterial.setEnabled(false);
        btnCancelarMaterial.setEnabled(true);
        btnEditarMaterial.setEnabled(false);
        btnExcluirMaterial.setEnabled(false);
        btnPesquisarMaterial.setEnabled(true);
        btnOkMaterial.setEnabled(true);

        // habilitar ou desabilitar texto
        txtNomeMaterial.setEnabled(false);
        txaDescricaoMaterial.setEnabled(false);
        txtTitulo.setEnabled(false);
        txtEditora.setEnabled(false);
        //txtTipo.setEnabled(false);
        txtAutores.setEnabled(false);
        txtAnoPublicacao.setEnabled(false);
        txtClassificacaoIndicativa.setEnabled(false);
        txtIdioma.setEnabled(false);
        txtQuantExemplares.setEnabled(false);
        
        txtCodAcervo.requestFocus(); 
        }
       */
    }//GEN-LAST:event_btnPesquisarMaterialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materiais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarMaterial;
    private javax.swing.JButton btnEditarMaterial;
    private javax.swing.JButton btnExcluirMaterial;
    private javax.swing.JButton btnFecharMaterial;
    private javax.swing.JButton btnNovoMaterial;
    private javax.swing.JButton btnOkMaterial;
    private javax.swing.JButton btnPesquisarMaterial;
    private javax.swing.JButton btnSalvarMaterial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblMateriais;
    private javax.swing.JTextArea txaDescricaoMaterial;
    private javax.swing.JTextField txtCodAcervo;
    private javax.swing.JTextField txtNomeMaterial;
    private javax.swing.JTextField txtQuantExemplares;
    // End of variables declaration//GEN-END:variables
}
